feat(tabs): add tabs component
cft-group/elephas-angular pull request #16
Opened 2020-08-24 08:37 UTC by Amil-Gaoul

В качестве заголовка табам можно передавать строку или html-контент через ng-template.

Ссылки и роутинг пока не закладывал. Такой сценарий возможен, но табы будут отображаться некорректно
```html
<e-tabs>
    <e-tab [title]="tab1">
        <ng-template #tab1>
            <a routerLink="/">Ссылка</a>
        </ng-template>
        Tab 1 content
    </e-tab>
</e-tabs>
```
Для роутинга пользователю или выкидывать событие через `@Output` или сделать возможность вставлять ссылки.

2020-08-24 08:59 UTC, apust requested changes

2020-08-24 08:59 UTC, apust commented on src/packages/core/src/tabs/tabs.stories.mdx
> +                            <svg viewBox="0 0 24 24" fill="#2962FF" width="24px" height="24px" xmlns="http://www.w3.org/2000/svg">
Предлагаю убирать из сторибука варианты с заведомо некрасивым дизайном, чтобы не натолкнуть других пользователей на мысль, что это допустимо. Как вариант, заменить SVG, которое ты вставляешь, на `e-badge`, который есть в макетах некоторых продуктов.

2020-08-24 09:01 UTC, apust commented
```
<ng-template #tab1>
    <a routerLink="/">Ссылка</a>
</ng-template>
```

@Amil-Gaoul, как насчёт `<a routerLink="/" eTab>Ссылка</a>`? Мы уже используем подобный подход [в кнопках](https://cft-group.github.io/elephas-angular/?path=/docs/core-button--default-story).

2020-08-24 09:05 UTC, apust commented on src/packages/core/src/tabs/tabs.stories.mdx
> +                            <svg viewBox="0 0 24 24" fill="#2962FF" width="24px" height="24px" xmlns="http://www.w3.org/2000/svg">
Как тут в третьей вкладке:

<img width="623" alt="Screenshot 2020-08-24 at 16 04 52" src="https://user-images.githubusercontent.com/2337671/91025421-90743480-e623-11ea-8f67-5f3219136e96.png">

2020-08-24 09:16 UTC, Amil-Gaoul commented
> ```
> <ng-template #tab1>
>     <a routerLink="/">Ссылка</a>
> </ng-template>
> ```
> 
> @Amil-Gaoul, как насчёт `<a routerLink="/" eTab>Ссылка</a>`? Мы уже используем подобный подход [в кнопках](https://cft-group.github.io/elephas-angular/?path=/docs/core-button--default-story).

Сейчас для всего этого надо компонент переделывать, да и класс `_e_tabs__item` должен вешаться на саму ссылку, а не внутри компонента применяться, так что тут надо подумать.

2020-08-26 04:39 UTC, Amil-Gaoul commented on src/packages/core/src/tabs/tabs.stories.mdx
> +                            <svg viewBox="0 0 24 24" fill="#2962FF" width="24px" height="24px" xmlns="http://www.w3.org/2000/svg">
Переделал на `e-badge`

2020-08-26 04:41 UTC, Amil-Gaoul commented
Сделал возможным передать в табы routerLink

2020-08-26 12:14 UTC, apust approved these changes

2020-08-27 09:53 UTC, gushinyakov approved these changes

2020-08-28 03:07 UTC, merged