feat(sidebar): add sidebar component
cft-group/elephas-angular pull request #28
Opened 2020-08-25 11:00 UTC by gushinyakov

2020-08-27 10:11 UTC, Amil-Gaoul requested changes

2020-08-27 10:11 UTC, Amil-Gaoul commented on src/packages/layout/src/sidebar/sidebar-badge.directive.ts
> +export class ESidebarBadgeDirective {
От directive, component в названии файлов и классов надо избавиться чтобы было по аналогии с другими компонентами в библиотеке

2020-08-27 10:11 UTC, Amil-Gaoul commented on src/packages/layout/src/sidebar/sidebar-item.directive.ts
> +            this.renderer.addClass(tooltipNode, '_e_tooltip');
А заюзать тултип из @elephas/angular-core не получится?

2020-08-27 10:11 UTC, Amil-Gaoul commented on src/packages/layout/src/sidebar/sidebar.stories.mdx
> +                <nav e-sidebar [isCollapse]="isSidebarCollapsed">
Может для компонентов, которые вешаем директивами тоже будем писать селекторы кэмелкейсом, чтобы в заблуждение не вводило. Хотя, я бы `e-sidebar` вставил бы компонентом, а `nav` утащил внутрь.

2020-08-27 10:48 UTC, apust commented on src/packages/layout/src/sidebar/sidebar-item.directive.ts
> +            this.renderer.addClass(tooltipNode, '_e_tooltip');
Должно получится. Тем более у нас `angular-core` в зависимостях у `angular-layout`.

2020-08-27 10:51 UTC, apust requested changes
Не увидел, где можно передать бейджик в SidebarItem. Возможно, плохо смотрел.

[В реакте вот так.](https://github.com/cft-group/elephas-react/blob/4cad012f263732cc826a95a40d11ae377dc9746b/src/packages/layout/src/sidebar/SidebarItem.tsx#L31-L35)

2020-10-07 07:13 UTC, gushinyakov commented
> Не увидел, где можно передать бейджик в SidebarItem. Возможно, плохо смотрел.
> 
> [В реакте вот так.](https://github.com/cft-group/elephas-react/blob/4cad012f263732cc826a95a40d11ae377dc9746b/src/packages/layout/src/sidebar/SidebarItem.tsx#L31-L35)

![image](https://user-images.githubusercontent.com/38750722/95299001-277d0f00-08a7-11eb-8309-67c35ddd1fa4.png)

Я подумал, что лучше добавить директиву для позиционирования компонента, а так можно любой badge component передать

2020-10-07 10:14 UTC, gushinyakov commented on src/packages/layout/src/sidebar/sidebar-badge.directive.ts
> +export class ESidebarBadgeDirective {
Исправил

2020-10-07 10:14 UTC, gushinyakov commented on src/packages/layout/src/sidebar/sidebar-item.directive.ts
> +            this.renderer.addClass(tooltipNode, '_e_tooltip');
Переделал с использование e-tooltip

2020-10-07 10:21 UTC, gushinyakov commented on src/packages/layout/src/sidebar/sidebar.stories.mdx
> +                <nav e-sidebar [isCollapse]="isSidebarCollapsed">
Переименовал. С nav не уверен, мне кажется неудобно, когда нативные теги скрыты

2021-02-05 08:35 UTC, merged