feat(dropdown): add dropdown component
cft-group/elephas-angular pull request #91
Opened 2020-09-09 11:40 UTC by Amil-Gaoul

- Переделал `base-input`, теперь это обертка над контролами: `input`, `select`, `textarea` и `dropdown`
- Все контролы вытащил наружу, это добавляет гибкости в их использовании и не надо переопределять ангуляровскую валидацию одним и тем же кодом как это было раньше.
- Добавил компонент `dropdown`

Из того что еще нужно сделать:
- Добавить отдельный класс для `dropdown`, чтобы в компоненте избавиться от инлайн-стилей как это сделано сейчас
- Добавить класс `_e_dropdwon__item_active` или другой более подходящий, когда пользователь перемещается по списку в `dropdown` с помощью клавиатуры, а то сейчас это не заметно совсем. Сам класс я добавил в библиотеку, но только для того чтобы проверить что функционал работает.
- Добавить класс `_e_dropdwon__item_selected`, чтобы можно было видеть выбранный ранее элемент, если пользователь кликнул по `dropdown и список раскрылся

Вопросы:
- При повторном открытии `dropdown` нужно ли скроллить до выбранного элемента или нет?
- Сколько все максимум должно отображаться элементов списка, чтобы не появлялся скролл? Или скролл вообще не делаем?

2020-09-14 04:30 UTC, gushinyakov commented on src/packages/core/src/base-input/base-input.html
> +        '_e_input_size_2': width === inputWidth.size2,
Можно так? 

ngOnInit() {
     inputWidth = `_e_input_size_${width}`
}

2020-09-14 04:30 UTC, gushinyakov commented on src/packages/core/src/base-input/base-input.ts
> +    encapsulation: ViewEncapsulation.None
OnPush?

2020-09-29 07:42 UTC, Amil-Gaoul commented on src/packages/core/src/base-input/base-input.html
> +        '_e_input_size_2': width === inputWidth.size2,
Как не пытался, но `ngClass` требует чтобы я написал класс и условие, такая конструкция не заработала
```html
[ngClass]="{
        '_e_input': true,
        '_e_input_appearance_disabled': disabled,
        '_e_input_appearance_readonly': readonly,
        '_e_input_appearance_error': hasError,
        '_e_select': isSelect,
        '_e_dropdown': isDropdown,
        inputWidth
}"
```
Я знаю что `ngClass` может принимать функцию или массив классов, но дело в том что должно быть что-то одно

2020-09-29 07:42 UTC, Amil-Gaoul commented on src/packages/core/src/base-input/base-input.ts
> +    encapsulation: ViewEncapsulation.None
Пофиксил

2020-10-07 11:50 UTC, apust commented
> При повторном открытии dropdown нужно ли скроллить до выбранного элемента или нет?
> Сколько всего максимум должно отображаться элементов списка, чтобы не появлялся скролл? Или скролл вообще не делаем?

Скроллить не нужно. Пока делаем максимум 5.

2020-12-09 02:21 UTC, apust commented on package.json
> +    "ngx-perfect-scrollbar": "^10.0.1",
Это точно не `dependencies`? Ведь без него не запустится приложение.

2020-12-09 02:46 UTC, apust commented on src/packages/core/src/dropdown/dropdown.ts
> +                    this.perfectScrollbar = new PerfectScrollbar(this.elementRef.nativeElement, { wheelSpeed: 0.1, wheelPropagation: false });
На тачпадах ноутов невозможно пользоваться скроллом внутри дропдауна, когда у него такие настройки.

2020-12-09 02:47 UTC, apust commented
Можно ли сделать опцию, которая будет блокировать ввод текста в инпут?

<img width="409" alt="image" src="https://user-images.githubusercontent.com/2337671/101567544-95f36000-3a03-11eb-97d7-456af8f22d93.png">

2020-12-09 02:49 UTC, apust commented
> Добавить отдельный класс для dropdown, чтобы в компоненте избавиться от инлайн-стилей как это сделано сейчас

Удалось решить этот вопрос?

2020-12-09 03:00 UTC, apust commented
По остальным стилям: будет достаточно этих?
https://github.com/cft-group/elephas/pull/86

2020-12-09 03:22 UTC, Amil-Gaoul commented on src/packages/core/src/dropdown/dropdown.ts
> +                    this.perfectScrollbar = new PerfectScrollbar(this.elementRef.nativeElement, { wheelSpeed: 0.1, wheelPropagation: false });
Ну а какие настройки ты предлагаешь? В Хроме и опере с wheelSpeed: 1 он вообще скроллит 50 элементов, если чуток колесо мышки крутануть. А wheelPropagation: false я поставил потому что меня бесит когда я доскроллил до конца списка и у меня его перехватывает родительский элемент. Когда малое количество элементов, например, 5-6 страничка поддергивается из-за этого

2020-12-09 03:24 UTC, Amil-Gaoul commented
> > Добавить отдельный класс для dropdown, чтобы в компоненте избавиться от инлайн-стилей как это сделано сейчас
> 
> Удалось решить этот вопрос? Сейчас не вижу инлайн стилей, кроме `display: none;`.

Нет, тут вообще какая проблема, как только с `input` пропадает фокус дропдаун закрывается. У меня в ангуляре даже клик  по элементу дропдауна не успевает сработать.

2020-12-09 03:24 UTC, Amil-Gaoul commented
> По остальным стилям: будет достаточно этих [cft-group/elephas#86](https://github.com/cft-group/elephas/pull/86)?
> <img alt="image" width="365" src="https://user-images.githubusercontent.com/2337671/101568640-8543e980-3a05-11eb-9170-cef8cdef2afa.png">

Думаю да

2020-12-09 04:33 UTC, Amil-Gaoul commented on package.json
> +    "ngx-perfect-scrollbar": "^10.0.1",
Попутал я что-то.

2020-12-09 04:50 UTC, Amil-Gaoul commented
> **UPDATE:** можно достичь желаемого результата, выставив аттрибут readonly элементу input: `<input readonly [...] />`.
> 
> Можно ли сделать опцию, которая будет блокировать ввод текста в инпут?
> 
> <img alt="image" width="409" src="https://user-images.githubusercontent.com/2337671/101567544-95f36000-3a03-11eb-97d7-456af8f22d93.png">

Блокировать по желанию? Или чтобы всегда блокировался ввод?

2020-12-09 08:12 UTC, apust commented on src/packages/core/src/dropdown/dropdown.ts
> +                    this.perfectScrollbar = new PerfectScrollbar(this.elementRef.nativeElement, { wheelSpeed: 0.1, wheelPropagation: false });
Мне надо протестировать. Чтобы по-честному, то склонировать на три ноута себе проект и с разными мышками и тачпадами в разных браузерах.

2020-12-09 08:14 UTC, apust commented
> Блокировать по желанию? Или чтобы всегда блокировался ввод?

Если у тебя там 100 элементов, то по-хорошему это надо превращать в Autocomplete: нет стрелки, но так же по фокусу виден список. И можно вводить текст, который отфильтрует результаты. См. сервисдеск ЦФТ (выбор компонента).

Если это выбор из 7 вещей в дропдауне, до блокируем. Работает аналогично системному "Select" на любой OS.

2020-12-09 08:38 UTC, Amil-Gaoul commented
> Если у тебя там 100 элементов, то по-хорошему это надо превращать в Autocomplete: нет стрелки, но так же по фокусу виден список. И можно вводить текст, который отфильтрует результаты. См. сервисдеск ЦФТ (выбор компонента).
> 
> Если это выбор из 7 вещей в дропдауне, до блокируем. Работает аналогично системному "Select" на любой OS.

Так в elephas же есть отдельный компонент `autocomplete` - https://cft-group.github.io/elephas/?path=/docs/core-autocomplete--default-story

Ну и вопрос: сколько должно быть минимально элементов, чтобы пользователь мог пользоваться дропдауном как автокомплитом?

2020-12-09 09:34 UTC, apust commented
> Я думал его стоит делать отдельным компонентом

Согласен. Тогда писать можно только в Autocomplete, в нём же вся логика. А Dropdown — это чисто замена Select-у, просто с красивыми стилями.

2020-12-09 09:46 UTC, apust commented on src/packages/core/src/dropdown/dropdown.ts
> +                    this.perfectScrollbar = new PerfectScrollbar(this.elementRef.nativeElement, { wheelSpeed: 0.1, wheelPropagation: false });
`wheelPropagation: false;` — значение по-умолчанию в `ngx-perfect-scrollbar`, судя по документации.
`wheelSpeed: 1;` (default) повторяет поведение скролла с той скоростью, с которой этот скролл работает на странице.

2020-12-09 10:36 UTC, Amil-Gaoul commented on src/packages/core/src/dropdown/dropdown.ts
> +                    this.perfectScrollbar = new PerfectScrollbar(this.elementRef.nativeElement, { wheelSpeed: 0.1, wheelPropagation: false });
> wheelPropagation: false; — значение по-умолчанию в ngx-perfect-scrollbar, судя по документации.
Я его на проекте `NinjaDojo` использовал и там не было ничего подобного, во всех дропдаунах как только я долистывал до конца списка скролл перехватывал родитель.

>wheelSpeed: 1; (default) повторяет поведение скролла с той скоростью, с которой этот скролл работает на странице.
Об этом можем поговорить с тестировщиком, который и тестировал его на проекте

Конкретно здесь используется не `ngx-perfect-scrollbar`, а `perfect-scrollbar`, который тянет уже `perfect-scrollbar`. Заюзать первый не получилось, потому что у самого компонента не задана `height` и `overflow`, `ngx-perfect-scrollbar` можно использовать как директиву или компонент, в первом случае проблема с тем что нет нужных стилей, со вторым будет вообще все плохо, потому что это дополнительная обертка ангуляровская и это скорее всего приведет к тому что поедут стили опять

2020-12-09 11:05 UTC, Amil-Gaoul commented on package.json
> +    "ngx-perfect-scrollbar": "^10.0.1",
Перетащил в `dependencies`

2020-12-09 11:13 UTC, Amil-Gaoul commented
> Т.е. тут всегда блокируем ввод.

Заблокировал ввод

2020-12-15 07:48 UTC, qworin commented
1. Дропдаун не реагирует на нажатие стрелок. Видно, что у EDropdownItem сетается свойство `active`, но сам класс не сетается. Мб стоит это свойство сделать реактивным.
2. В EDropdownTriggers на строке 38 светится ошибка `'keyCode' is deprecated`. Возможно, стоит использовать [что-нибудь другое](https://stackoverflow.com/questions/35394937/keyboardevent-keycode-deprecated-what-does-this-mean-in-practice)
3. Неплохо ещё добавить обработчик на пробел, как в нативном селекте. Чтоб при фокусе на инпуте пробел открывал дропдаун.
4. Курсор над инпутом выдает текстовый инпут с головой.
5. У компонента не хватает свойства required, благодаря которому в списке не должно быть пустого значения.
5.1. Мб стоит сделать сбрасывающую значение кнопочку-крестик вместо пустой опции? Тогда при required её просто не показывать.
6. Для options следует использовать интерфейс `{label: string; value: any}`. Показывать лейблы, а эмитить значения. Насколько можно видеть, это [широко распространено](https://bit.dev/components?q=dropdown).
7. Мб я вперёд забегаю, но будет ли тут [разбитие опций по группам](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/optgroup)?

2020-12-15 10:03 UTC, Amil-Gaoul commented
> 1. Дропдаун не реагирует на нажатие стрелок. Видно, что у EDropdownItem сетается свойство `active`, но сам класс не сетается. Мб стоит это свойство сделать реактивным.

Потому что мы ждем когда смерджится пуллреквест в другой либе https://github.com/cft-group/elephas/pull/86 и будет релиз
> 2. В EDropdownTriggers на строке 38 светится ошибка `'keyCode' is deprecated`. Возможно, стоит использовать [что-нибудь другое](https://stackoverflow.com/questions/35394937/keyboardevent-keycode-deprecated-what-does-this-mean-in-practice)

Оно сделано под константы angular cdk, собственно у них в гайде `keyManager` так и работает, в другом случае все придется переделывать.
> 5. У компонента не хватает свойства required, благодаря которому в списке не должно быть пустого значения.
>    5.1. Мб стоит сделать сбрасывающую значение кнопочку-крестик вместо пустой опции? Тогда при required её просто не показывать.

На мой взгляд эта задача уже для ангуляровской валидации, тут оно не нужно.

> 7. Мб я вперёд забегаю, но будет ли тут [разбитие опций по группам](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/optgroup)?

Я бы оставил на будущее.

2020-12-16 04:40 UTC, apust commented
> > 1. Дропдаун не реагирует на нажатие стрелок. Видно, что у EDropdownItem сетается свойство active, но сам класс не сетается. Мб стоит это свойство сделать реактивным.
> 
> Потому что мы ждем когда смерджится пуллреквест в другой либе cft-group/elephas#86 и будет релиз

Done: https://github.com/cft-group/elephas/releases/tag/v1.4.3

-----------

> 7. Мб я вперёд забегаю, но будет ли тут разбитие опций по группам?

Пока не предусмотрено в дизайне, т.к. не было необходимости ни в одном из проектов. Строго говоря, даже в ненативном селекте не было необходимости :)

2020-12-16 04:50 UTC, apust commented
> 5.1. Мб стоит сделать сбрасывающую значение кнопочку-крестик вместо пустой опции? Тогда при required её просто не показывать.

Сбрасывающая кнопочка — хорошо. В дизайне предусмотрено использование нескольких иконок рядом в инпуте:
<img width="425" alt="image" src="https://user-images.githubusercontent.com/2337671/102306239-58a74900-3f94-11eb-8a0a-88716217002a.png">

Она лучше пустой опции. Если есть возможность, то можно реализовать.

Но она не должна пропадать, даже если поле `required`. Она сделает поле пустым, поле загорится красным.

2020-12-16 05:34 UTC, Amil-Gaoul commented
> 4. Курсор над инпутом выдает текстовый инпут с головой.

Ему можно было бы задать `type=button`. И тогда проблема бы с курсором решилась. Но появится тогда проблема с плейсхолдером, потому что тут все на стили завязано. Плейсхолдер всегда вверху будет
![image](https://user-images.githubusercontent.com/16349083/102309288-0ae20f00-3f9b-11eb-9199-e5975faf34be.png)

2020-12-16 06:49 UTC, apust commented
> Ему можно было бы задать type=button. И тогда проблема бы с курсором решилась. Но появится тогда проблема с плейсхолдером, потому что тут все на стили завязано. Плейсхолдер всегда вверху будет

Решается стилем, но тогда и текст будет пропадать, что не очень.
```css
._e_dropdown ._e_input__control:focus {
  color: transparent;
}
```

2020-12-16 08:49 UTC, Amil-Gaoul commented
> Решается стилем, но тогда и текст будет пропадать, что не очень.
> 
> ```css
> ._e_dropdown ._e_input__control:focus {
>   color: transparent;
> }
> ```

А если так?
```css
._e_dropdown ._e_input__control {
  cursor: default;
}
```

2020-12-18 09:39 UTC, Amil-Gaoul commented on src/packages/core/src/dropdown/dropdown.ts
> +                    this.perfectScrollbar = new PerfectScrollbar(this.elementRef.nativeElement, { wheelSpeed: 0.1, wheelPropagation: false });
Переделал скроллбар через директиву с дефолтными настройками

2020-12-18 09:50 UTC, Amil-Gaoul commented
>1. Дропдаун не реагирует на нажатие стрелок. Видно, что у EDropdownItem сетается свойство active, но сам класс не сетается. Мб стоит это свойство сделать реактивным.

Переделал, стрелки теперь работают

>2. В EDropdownTriggers на строке 38 светится ошибка 'keyCode' is deprecated. Возможно, стоит использовать что-нибудь другое

Переделал через `event.code`, который возвращает строку.

>3. Неплохо ещё добавить обработчик на пробел, как в нативном селекте. Чтоб при фокусе на инпуте пробел открывал дропдаун.

Теперь по нажатию на пробел дропдаун показывается/скрывается, когда фокус на инпуте

>4. Курсор над инпутом выдает текстовый инпут с головой.

Это уже не от меня зависит. Надо править стили

>5. У компонента не хватает свойства required, благодаря которому в списке не должно быть пустого значения.
>5.1. Мб стоит сделать сбрасывающую значение кнопочку-крестик вместо пустой опции? Тогда при required её просто не показывать.

Как появится иконка с крестиком сделаю

>6. Для options следует использовать интерфейс {label: string; value: any}. Показывать лейблы, а эмитить значения. Насколько можно видеть, это широко распространено.

Сделал как в ангуляр материал, т.е. теперь это рабочий вариант:
```html
<e-dropdown-item *ngFor="let option of options" [value]="option.value">{{ option.value }}</e-dropdown-item>
```

>7. Мб я вперёд забегаю, но будет ли тут разбитие опций по группам?

Пока оставил на будущее

2020-12-24 03:29 UTC, apust commented on src/packages/core/CHANGELOG.md
> +# [1.0.0-beta.0](https://github.com/cft-group/elephas-angular/compare/v1.0.0-alpha.5...v1.0.0-beta.0) (2020-12-14)
Каким образом в пуллреквесте оказался автоматически генерирующийся при релизе чейнджлог?

2020-12-24 03:30 UTC, apust commented on src/packages/core/package.json
> +  "version": "1.0.0-beta.0",
Это тоже не должно появляться в пулл реквесте

2020-12-24 09:16 UTC, apust requested changes
В пулл-реквест как-то закрались последние изменения из мастера, вроде обновлений версии в `package.json`, файлов компонента `Snackbar` и изменений чейнджлога. Их надо убрать из пулл-реквеста.

2020-12-24 09:18 UTC, apust commented
Для сброса значения предлагаю вместо иконки-крестика использовать пункт с кастомизируемым текстом и пустым value, как в Angular Material: https://material.angular.io/components/select/overview

```HTML
<mat-form-field appearance="fill">
  <mat-label>Select an option</mat-label>
  <mat-select [(value)]="selected">
    <mat-option>None</mat-option>
    <mat-option value="option1">Option 1</mat-option>
    <mat-option value="option2">Option 2</mat-option>
    <mat-option value="option3">Option 3</mat-option>
  </mat-select>
</mat-form-field>
```

2020-12-24 10:28 UTC, apust requested changes

2020-12-24 10:28 UTC, apust commented on src/packages/core/src/dropdown/dropdown.stories.mdx
> +                        <e-dropdown-item *ngFor="let option of options" [value]="option.value">{{ option.value }}</e-dropdown-item>
Давайте поменяем на
```
<e-dropdown-item *ngFor="let option of options" [value]="option.value">
  {{ option.title }}
</e-dropdown-item>
```

2020-12-24 10:28 UTC, apust commented on src/packages/core/src/dropdown/dropdown.stories.mdx
> +                    }, {
Давайте поменяем на
```js
options: [
  { value: '', title: 'None' },
  { value: 'one', title: 'One' },
]
```

2020-12-24 10:30 UTC, apust commented on src/packages/core/src/dropdown/dropdown.stories.mdx
> +                    <input eInput [eDropdownTriggers]="eDropdown">
Если смочь вот тут передать html-ному инпуту аттрибут `readonly` без дополнительных стилей элефаса, то пропадёт мигающий курсор и возможность вводить текст. Есть возможность это сделать?

2020-12-24 10:52 UTC, Amil-Gaoul commented on src/packages/core/src/dropdown/dropdown.stories.mdx
> +                    <input eInput [eDropdownTriggers]="eDropdown">
Так на него и так вешается `readonly`, чтобы пользователь не мог ничего ввести в `input`, класс `_e_input_appearance_readonly` не тянется, но курсор же мигает.
![image](https://user-images.githubusercontent.com/16349083/103084092-b250e880-4610-11eb-8e4f-69416e29c218.png)

2020-12-24 10:54 UTC, Amil-Gaoul commented on src/packages/core/src/dropdown/dropdown.stories.mdx
> +                    <input eInput [eDropdownTriggers]="eDropdown">
В общем, я уже как-то пытался высказать мысль что надо избавиться от всех `css` свойств с помощью которых сделан `floating label`, `dropdown` открывается и разруливать все это через скрипты, потому что иначе оно только дополнительный геморрой создает.

2020-12-24 11:25 UTC, apust commented on src/packages/core/src/dropdown/dropdown.stories.mdx
> +                    <input eInput [eDropdownTriggers]="eDropdown">
Про CSS согласен. Выяснилось, что я где-то протупил с гитом, и смотрел не ту версию. Смотрю самую последнюю, в Сафари и Хроме курсор не моргает, текст вводить нельзя, все работает как надо. И `wheelPropagation: false` надо все-таки вернуть, тут я был не прав на счёт поведения по-умолчанию.

2020-12-29 08:33 UTC, apust commented
@Amil-Gaoul, в [`@elephas/core@1.6.0`](https://github.com/cft-group/elephas/releases/tag/v1.6.0) появился модификатор `._e_input_focused`, который можно использовать вместо стандартного фокуса в инпуте.

2021-01-27 10:37 UTC, Amil-Gaoul commented on src/packages/core/src/dropdown/dropdown.stories.mdx
> +                    }, {
Добавил в списке `title`

2021-01-27 10:37 UTC, Amil-Gaoul commented on src/packages/core/src/dropdown/dropdown.stories.mdx
> +                        <e-dropdown-item *ngFor="let option of options" [value]="option.value">{{ option.value }}</e-dropdown-item>
Поменял

2021-01-27 10:40 UTC, Amil-Gaoul commented
> В пулл-реквест как-то закрались последние изменения из мастера, вроде обновлений версии в `package.json`, файлов компонента `Snackbar` и изменений чейнджлога. Их надо убрать из пулл-реквеста.

Видимо когда коммитил в прошлый раз накосячил, сейчас от лишних файлов избавился.



> @Amil-Gaoul, в [`@elephas/core@1.6.0`](https://github.com/cft-group/elephas/releases/tag/v1.6.0) появился модификатор `._e_input_focused`, который можно использовать вместо стандартного фокуса в инпуте.

Переписал появление дропдауна через класс. С `perfectScrollbar` получилось не очень хорошо, поправил обертку, чтобы класс `_e_dropdown__card` на нее ложился, но лишний `div` внутри все равно пришлось добавить

2021-01-29 02:07 UTC, apust requested changes

2021-01-29 02:07 UTC, apust commented on package.json
> +    "ngx-perfect-scrollbar": "^10.0.1",
В корне в `dependencies` добавил `ngx-perfect-scrollbar`, а в `peerDependencies` к пакету `@elephas/angular-core` не добавил.

2021-01-29 02:08 UTC, apust approved these changes

2021-01-29 02:09 UTC, merged